import { PortfolioItem } from "@/types";

export const PORTFOLIO_DATA: PortfolioItem[] = [
  {
    id: "1",
    slug: "White-Green-Wedding",
    title: "White Green Wedding",
    category: "wedding",
    cover: "/images/wedding/img10.JPG",
    images: [
      "/images/wedding/img8.JPG",
      "/images/wedding/img1.JPG",
      "/images/wedding/img22.JPG",
      "/images/wedding/img6.JPG",
      "/images/wedding/img7.JPG",
      "/images/wedding/img9.JPG",
      "/images/wedding/img10.JPG",
      "/images/wedding/img11.JPG",
      "/images/wedding/img15.JPG",
      "/images/wedding/img16.JPG",
      "/images/wedding/img18.JPG",
      "/images/wedding/img19.JPG",
      "/images/wedding/img20.JPG",
      "/images/wedding/img21.JPG",
      "/images/wedding/img23.JPG",
      "/images/wedding/img24.JPG",
      "/images/wedding/img25.JPG",
    ],
    description: "Elegant whites and greens with airy textures.",

  },

  {
    id: "2",
    slug: "elegant-bouquet",
    title: "Elegant Bouquet",
    category: "bouquet",
    cover: "/images/bouquet/img7.jpg",
    images: [
      "/images/bouquet/img.JPG",
      "/images/bouquet/img2.jpg",
      "/images/bouquet/img3.jpg",
      "/images/bouquet/img4.jpg",
      "/images/bouquet/img5.jpg",
      "/images/bouquet/img7.jpg",
      "/images/bouquet/IMG_0191.jpg",
      "/images/bouquet/IMG_3058.jpg",
      "/images/bouquet/IMG_6606.jpg",
      "/images/bouquet/IMG_7616.jpg",
      "/images/bouquet/IMG_7660.jpg",
      "/images/bouquet/IMG_8399.jpg",
    ],
    description: "A timeless bouquet with soft textures and elegant colors.",
  },

  {
    id: "3",
    slug: "baby-shower",
    title: "Baby Shower Celebration",
    category: "event",
    cover: "/images/baby-shower/IMG78.JPG",
    images: [
      "/images/baby-shower/IMG.JPG",
      "/images/baby-shower/IMG1.JPG",
      "/images/baby-shower/IMG2.JPG",
      "/images/baby-shower/IMG3.JPG",
      "/images/baby-shower/IMG4.JPG",
      "/images/baby-shower/IMG5.JPG",
      "/images/baby-shower/IMG6.JPG",
      "/images/baby-shower/IMG7.JPG",
      "/images/baby-shower/IMG9.JPG",
      "/images/baby-shower/IMG10.JPG",
      "/images/baby-shower/IMG11.JPG",
      "/images/baby-shower/IMG12.JPG",
      "/images/baby-shower/IMG13.JPG",
      "/images/baby-shower/IMG14.JPG",
      "/images/baby-shower/IMG78.JPG",
    ],
    description: "Yellow and purple florals and decorations for a cheerful celebration.",
  },
  {
    id: "4",
    slug: "floral-arrangements",
    title: "Floral Arrangements",
    category: "bouquet",
    cover: "/images/bouquet1.jpeg",
    images: [
      "/images/bouquet/photo-18.jpg",
      "/images/bouquet/IMG_2223.jpg",
      "/images/wedding1/IMG_3002.jpg",
      "/images/wedding1/IMG_1664.jpg",
      "/images/wedding1/IMG_1668.jpg",
      "/images/wedding1/photo_9.jpeg",
    ],
    description: "Beautifully crafted floral arrangements for various occasions.",
  },

  {
    id: "5",
    slug: "birthday-party",
    title: "Birthday Party",
    category: "event",
    cover: "/images/birthday/img11.jpg",
    images: [
      "/images/birthday/img.jpg",
      "/images/birthday/img1.jpg",
      "/images/birthday/img2.jpg",
      "/images/birthday/img7.jpg",
      "/images/birthday/img12.jpg",
      "/images/birthday/img13.jpg",
      "/images/birthday/img14.jpg",
      "/images/birthday/img15.jpg",
      "/images/birthday/img16.jpg",
      "/images/birthday/img17.jpg",
      "/images/birthday/img18.jpg",
      "/images/birthday/img19.jpg",
      "/images/birthday/img21.jpg",
      "/images/birthday/img22.jpg",
    ],
    description: "Joyful birthday celebration with colorful arrangements.",
  },
  {
    id: "6",
    slug: "workshop",
    title: "Spring Floral Workshop",
    category: "event",
    cover: "/images/workShop/photo-63.jpg",
    images: [
      "/images/workShop/photo-50.jpg",
      "/images/workShop/photo-51.jpg",
      "/images/workShop/photo-52.jpg",
      "/images/workShop/photo-69.jpg",
      "/images/workShop/photo-70.jpg",
      "/images/workShop/photo-133.jpg",
      "/images/workShop/photo-137.jpg",
      "/images/workShop/photo-63.jpg",
    ],
    description: "Spring floral arrangement workshop with pastel tones.",
  },

  {
    id: "7",
    slug: "elegant-wedding",
    title: "Elegant Wedding",
    category: "wedding",
    cover: "/images/wedding1/photo_7.jpeg",
    images: [
      "/images/wedding1/photo_1.jpeg",
      "/images/wedding1/photo_2.jpeg",
      "/images/wedding1/photo_3.jpeg",
      "/images/wedding1/photo_4.jpeg",
      "/images/wedding1/photo_5.jpeg",
      "/images/wedding1/photo_6.jpeg",
      "/images/wedding1/photo_7.jpeg",
      "/images/wedding1/photo_8.jpeg",
      "/images/wedding1/photo_9.jpeg",
      "/images/wedding1/photo_10.jpeg",
      "/images/wedding1/photo_11.jpeg",
      "/images/wedding1/photo_12.jpeg",
      "/images/wedding1/photo_13.jpeg",
      "/images/wedding1/photo_14.jpeg",
      "/images/wedding1/img.JPG",
      "/images/wedding1/IMG_1664.jpg",
      "/images/wedding1/IMG_1668.jpg",
      "/images/wedding1/IMG_1699.jpg",
      "/images/wedding1/IMG_1704.jpg",
      "/images/wedding1/IMG_3002.jpg",
      "/images/wedding1/IMG_3009.jpg",
      "/images/wedding1/IMG_3010.jpg",
    ],
    description: "Charming elegant wedding with classic floral designs.",
  },

  {
    id: "8",
    slug: "installations",
    title: "Installations",
    category: "bouquet",
    cover: "/images/instalation/img10.JPG",
    images: [
      "/images/instalation/img10.JPG",
      "/images/instalation/img19.JPG",
      "/images/instalation/img20.JPG",
      "/images/instalation/img23.JPG",
      "/images/instalation/img8.JPG",
      "/images/instalation/photo_2025-10-16 10.27.29.jpeg",
    ],
    description: "Professional floral installations and venue decorations.",
  },
  {
    id: "9",
    slug: "workshop",
    title: "Fall Floral Workshop",
    category: "event",
    cover: "/images/fall/photo-12.jpg",
    images: [
      "/images/fall/photo-3.jpg",
      "/images/fall/photo-4.jpg",
      "/images/fall/photo-6.jpg",
      "/images/fall/photo-7.jpg",
      "/images/fall/photo-9.jpg",
      "/images/fall/photo-10.jpg",
      "/images/fall/photo-23.jpg",
      "/images/fall/photo-12.jpg",
      "/images/fall/photo-27.jpg",
      "/images/fall/photo-33.jpg",
      "/images/fall/photo-34.jpg",
      "/images/fall/photo-35.jpg",
      "/images/fall/photo-36.jpg",
      "/images/fall/photo-37.jpg",
      "/images/fall/photo-38.jpg",
      "/images/fall/photo-39.jpg",
      "/images/fall/photo-42.jpg",
      "/images/fall/photo-46.jpg",

    ],
    description: "Seasonal fall floral arrangement workshop with warm tones.",
  }

];